### PR TITLE
Create a set of hicolor icons with improved visibility

### PR DESCRIPTION
**Pull request by tari01**
fixes https://github.com/AyatanaIndicators/ayatana-indicator-keyboard/issues/63

### CODE REVIEW

**Comment by sunweaver** [comment]
Please leave the high-contrast icons for now. We need them in our customer project. Remember that we use a distro where upstream improvements don't land very fast. So, as long as HighContrast does not ship those icons, we should provide them.

Btw.: Have you approach HighContrast icon theme maintainers regarding adoption of those icons? If not, please do.

**Comment by sunweaver** [comment]
Regarding the new icon set: can we center the language code a little more? Plus: to me a sanserif font would seem more appropriate. What do you think?

**Comment by tari01** [comment]
> Please leave the high-contrast icons for now. We need them in our customer project. Remember that we use a distro where upstream improvements don't land very fast. So, as long as HighContrast does not ship those icons, we should provide them.
> 
> Btw.: Have you approach HighContrast icon theme maintainers regarding adoption of those icons? If not, please do.

On second thought, it is best to leave these in. Since there is not official High Contrast theme project, it looks like every application that cares about accessibility simply provides these icons. While `ContrastHigh` comes with the default MATE themes, it contains only a small subset of standard icons, so no point in knocking on that door.

**Comment by tari01** [comment]
> Regarding the new icon set: can we center the language code a little more? Plus: to me a sanserif font would seem more appropriate. What do you think?

Generator script updated and Icons re-aligned. As for the font, the icons **are Sans**. I guess you viewed them trough GitHub in the browser? For some reason it uses whatever font it wants.

**Pull request merged**
