### PR TITLE
src/service.c: Add tooltip.

### PR DESCRIPTION
**Pull request by sunweaver**

### CODE REVIEW

**Comment by sunweaver** [comment]
@flexiondotorg It would be nice to get your feedback on this as a English native speaker. Thanks.

**Comment by sunweaver** [comment]
@tari01: ping for review (keyboard indicator #40).

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
"Keyboard layout switcher and settings" would read better IMO.

**Comment by sunweaver** [comment]
> "Keyboard layout switcher and settings" would read better IMO.

Done.

**Pull request merged**
