### PR TITLE
Add Lomiri icon generator

### PR DESCRIPTION
**Pull request by tari01**

### CODE REVIEW

**Review by sunweaver — CHANGES_REQUESTED** [review]
The "Add Lomiri icon generator" commit LGTM.

However, I wonder why we ship the ayatana-indicator-keyboard-icon-generator-lomiri in the data/ folder. As I see it, we need the script during build time, right?

Then, I think the project's base folder (or a scripts/ subfolder) is the better place for this script to live in. This possibly also applies to the living place of the ayatana-indicator-keyboard-icon-generator-script.

I sense that both scripts should be moved to ./ or ./scripts/. And maybe also let's have a file extension for both scripts (i.e. a .py).

**Comment by tari01** [comment]
> As I see it, we need the script during build time, right?

We don't. We ship a default set of pre-built hicolor icons. These are tools for packagers.

> I sense that both scripts should be moved to ./ or ./scripts/. And maybe also let's have a file extension for both scripts (i.e. a .py).

I can move them to /scripts (or maybe /tools?) with *.py

**Comment by sunweaver** [comment]
> > As I see it, we need the script during build time, right?
> 
> We don't. We ship a default set of pre-built hicolor icons. These are tools for packagers.

Ah, ok. I remember.

> > I sense that both scripts should be moved to ./ or ./scripts/. And maybe also let's have a file extension for both scripts (i.e. a .py).
> 
> I can move them to /scripts (or maybe /tools?) with *.py

If they are not part of any build and not used during make install, I'd suggest contrib/, in fact.

**Comment by sunweaver** [comment]
@tari01: Please rebase this branch, there is something odd with the commits on this branch.

**Comment by tari01** [comment]
> @tari01: Please rebase this branch, there is something odd with the commits on this branch.

Ready to go.

**Pull request merged**
